### ISSUE TITLE
CITE-seq data loading

### ISSUE THREAD

**Issue by parkcc** [YosefLab/scVI#565] opened 2020-01-29 00:03 UTC
Hi, I am trying to load a local 10X dataset in order to try and execute your TOTALVI pipeline (we are looking at CITE-seq data).  

Beautiful work BTW!

I can see that it loads; however it then seems to hang....I've posted some errors below.
Does anyone have any suggestions on running our own 10X CITEseq data through TOTALVI?

I did notice another form of CITEseq data...instead of using the 10X filtered_gene_bc_matrices and its affiliated files, the other form of CITEseq data as an input.  Would you recommend one over the other?

Many thanks,
Chris Park

######

local_10X_dataset = Dataset10X(
    dataset_name="SET_1",
    save_path=os.path.join(save_path, "10X/SET_1/"),
    measurement_names_column=1,
    dense=True,
)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-3bfe91ee7b5d> in <module>
      3     save_path=os.path.join(save_path, "10X/SET_1/"),
      4     measurement_names_column=1,
----> 5     dense=True,
      6 )

/opt/anaconda3/lib/python3.7/site-packages/scvi-0.5.0-py3.7.egg/scvi/dataset/dataset10X.py in __init__(self, dataset_name, filename, save_path, url, type, dense, measurement_names_column, remove_extracted_data, delayed_populating)
    130             if filename is not None:
    131                 logger.warning("dataset_name provided, manual filename is disregarded.")
--> 132             group = dataset_to_group[dataset_name]
    133             url_skeleton = group_to_url_skeleton[group]
    134             url = url_skeleton.format(group, dataset_name, dataset_name, type)

KeyError: 'SET_1'

To load from an AnnData object with "protein_expression" obsm and "protein_names" uns

from scvi.dataset import AnnDatasetFromAnnData, CellMeasurement

anndataset = anndata.read(save_path + "filename.h5ad")
dataset = AnnDatasetFromAnnData(ad=anndataset)
protein_data = CellMeasurement(
    name="protein_expression",
    data=anndataset.obsm["protein_expression"].astype(np.float32),
    columns_attr_name="protein_names",
    columns=anndataset.uns["protein_names"],
)
dataset.initialize_cell_measurement(protein_data)
In general, protein data can be added to any GeneExpressionDataset through the .initialize_cell_measurement(.) method as shown above.

**Comment by adamgayoso** [comment] 2020-01-29 01:39
This appears to be a data loading issue. I'll admit loading from 10x is not the most intuitive. I believe the issue is that you don't need to specify the dataset_name option so long as `10X/SET_1/` contains the data files.

In general, I recommend using scanpy to load the data and making an anndata object, which you can load into scVI/totalVI using the code at the bottom of your issue (and this one). Saving this anndata for later is ideal as it's much faster to save/load from these compared to the 10x outputs.

```python
import scanpy as sc
import numpy as np

anndataset = sc.read_10x_mtx(save_path, gex_only=False)
anndataset.obsm["protein_expression"] = anndataset[
    :, anndataset.var["feature_types"] == "Antibody Capture"
].X.A
anndataset.uns["protein_names"] = np.array(
    anndataset.var_names[anndataset.var["feature_types"] == "Antibody Capture"]
)
anndataset = anndataset[
    :, anndataset.var["feature_types"] != "Antibody Capture"
].copy()
anndataset.X = anndataset.X.A
anndataset.var_names_make_unique()

dataset = AnnDatasetFromAnnData(ad=anndataset)
protein_data = CellMeasurement(
name="protein_expression",
data=anndataset.obsm["protein_expression"].astype(np.float32),
columns_attr_name="protein_names",
columns=anndataset.uns["protein_names"],
)
dataset.initialize_cell_measurement(protein_data)
```

**Comment by adamgayoso** [comment] 2020-01-30 18:20
I'm closing the issue, but please feel free to make issues if there is any other confusion.

**Closed by adamgayoso** 2020-01-30 18:20 UTC
