### ISSUE TITLE
Question: Pitfalls of using `n_iter_kl_warmup=0`?

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scVI#735] opened 2020-08-26 19:46 UTC
Hello, I'm training some larger models, and they were getting stuck in the warmup phase - that's when I realized, looking at the documentation string copied below, that I shouldn't be relying on the default and instead should be setting `n_iter_kl_warmup` directly. The documentation below suggests setting it to `128*5000/400` = 1600, why is that?

I tried finding some reference on what are the possible pitfalls of skipping it altogether (setting `n_iter_kl_warmup=0`), but couldn't pinpoint anything. Could you suggest where to look or share what has been your experience on this?

Thanks! 

```
    Other Parameters
    ----------------
    n_epochs_kl_warmup
        Number of epochs for linear warmup of KL(q(z|x)||p(z)) term. After `n_epochs_kl_warmup`,
        the training objective is the ELBO. This might be used to prevent inactivity of latent units, and/or to
        improve clustering of latent space, as a long warmup turns the model into something more of an autoencoder.
        Be aware that large datasets should avoid this mode and rely on n_iter_kl_warmup. If this parameter is not
        None, then it overrides any choice of `n_iter_kl_warmup`.
    n_iter_kl_warmup
        Number of iterations for warmup (useful for bigger datasets)
        int(128*5000/400) is a good default value.
```

**Comment by adamgayoso** [comment] 2020-08-27 01:04
Basically warmup was designed to prevent latent variable collapse/dying units problem. Researchers had noticed that the number of "active" latent dimensions was quite small and that warmup could prevent these local optima or lead to better representations (see [ladder vaes](https://arxiv.org/pdf/1602.02282.pdf)). We've found warmup useful for these reasons.

The issue is when you have massive single cell datasets where scVI converges in <20 epochs, a 400 epoch warmup doesn't make much sense. As a result we introduce the iter warmup, where 1 iter is one minibatch. That default is equivalent to the number of iterations a dataset of 500 cells would go through in 400 epochs, so we reasoned this is a fine default. Though we haven't done extensive testing of this.

That said, we've also seen instances where warmup is not necessary, so I guess I'd try it both ways.

**Comment by adamgayoso** [comment] 2020-08-28 01:16
I'll close this issue, but if you find anything interesting with these parameters please let us know!

**Closed by adamgayoso** 2020-08-28 01:16 UTC
Labels: question

**Comment by davemcg** [comment] 2020-09-27 19:02
I'm a bit confused. If I have ~1e6 cells, I've been using `n_epochs` of 1-5. What do you recommend setting `n_iter_kl_warmup` to? 1-5? 0?

**Comment by adamgayoso** [comment] 2020-09-29 14:34
I would try setting n epochs kL warmup to None and n iter to the recommended value in the doc string.
