### ISSUE TITLE
Error loading functions from autotune.py

### ISSUE THREAD

**Issue by ilyakorsunsky** [YosefLab/scVI#336] opened 2019-05-15 17:33 UTC
I am having trouble loading things from scvi.inference.autotune, such as auto_tune_scvi_model:

from scvi.inference import UnsupervisedTrainer, auto_tune_scvi_model
ImportError: cannot import name 'auto_tune_scvi_model' from 'scvi.inference' 

I installed scvi through the bioconda repo and directly through github and got the same error with both. 

Great method, look forward to using it!

**Comment by jeff-regier** [comment] 2019-05-15 19:26
Hi Ilya, Thanks for trying out scVI! We just recently added automatic hyperparameter tuning to the master branch of scVI; the version of scVI that conda installs from earlier.

@romain-lopez Perhaps you would release a new version of scVI (0.4 ?) in a couple of days, or whenever @gabmis releases his blog post on scVI's automatic hyperparameter tuning?

Ilya, in the meantime you might try using the master branch of scVI rather than the version conda installs. You'd need to install a couple of additional dependencies too that we've added since releasing scVI v0.3. Those additional dependencies you can install with ``conda install pymongo hyperopt scanpy louvain -c conda-forge``.

**Comment by romain-lopez** [comment] 2019-05-16 17:16
Sounds good, let me know Gabriel when you want to release a new version !

Best,
Romain

**Comment by jeff-regier** [comment] 2019-05-21 15:39
Hi Ilya, I see you now you said you tried installing the version of scVI on github too. With that version, I'm surprised you'd get the same import. Is it possible that even though you downloaded the github version, you're python path is such that you're still important the version of scVI that conda installed? Would you try it again (with the latest version of scVI master branch) after typing `conda remove scvi` ?

**Comment by jeff-regier** [comment] 2019-05-21 15:41
On my machine:
```
(base) 587233495:scVI jeff$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scvi.inference import UnsupervisedTrainer, auto_tune_scvi_model
/Users/jeff/miniconda3/lib/python3.7/site-packages/sklearn/utils/linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  DeprecationWarning)
>>> 
```

**Comment by RicedeKrispy** [comment] 2019-06-05 16:59
I'm having the same issue, after trying all the suggestions above. Would love some advice.

**Comment by jeff-regier** [comment] 2019-06-05 17:07
We're planning to release a new version of scVI in the next few days that will include automatic hyperparameter tuning, as well as a blog post showing how to use it.

**Comment by by-young** [comment] 2019-06-17 13:30
I also have the same problem on importing the 'auto_tune_scvi_model' module. I also try to download the install package to the service and run the command to install the scVI. But the problem is still there.

**Comment by gabmis** [comment] 2019-06-17 16:24
Hi,
Thank you for your interest in scVI!
While waiting for the new release which should happen in the coming weeks, you may try to install from source as follows (if you use ssh):
```bash
git@github.com:YosefLab/scVI.git
cd scVI
python setup.py install
```

**Comment by gabmis** [comment] 2019-06-17 16:27
This discussion will be useful for people having the same issue but doesn't require anything on our part, therefore I am closing it.

**Comment by RicedeKrispy** [comment] 2019-06-17 19:30
Thanks. I tried this, and the result:

"ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository

Please make sure you have the correct access rights and the repository exists."

**Comment by gabmis** [comment] 2019-06-17 19:53
Alternately, you can try

```bash
git clone https://github.com/YosefLab/scVI.git
```

Ultimately, please refer to the GitHub documentation for help with repository cloning: https://github.com/YosefLab/scVI.git

**Comment by RicedeKrispy** [comment] 2019-06-17 20:29
Thanks for the prompt response. Now the following error is thrown:

"The package setup script has attempted to modify files on your system that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not support alternate installation locations even if you run its setup by hand. Please inform the package's author and the EasyInstall maintainers to find out if a fix or workaround is available."

**Comment by romain-lopez** [comment] 2019-06-28 20:36
Is the last issue from RicedeKrispy related to issue #378 ?

**Closed** 2019-07-18 21:21 UTC
