### ISSUE TITLE
update_cells not updating all features

### ISSUE THREAD

**Issue by chenlingantelope** [YosefLab/scVI#583] opened 2020-02-14 00:33 UTC
update_cells does not change 
* cell_types
* labels
* n_labels
* batch_indices
if subsetting by batch and the number of cell types also change 
There might be something else as well because when training scvi on a dataset that I ran update_cells on, the cost function keep returning NA.

**Comment by adamgayoso** [comment] 2020-03-11 00:20
Any interest in looking into this @ANazaret ? Any help is appreciated!

**Comment by ANazaret** [comment] 2020-03-11 02:38
Hi Chenling, 
Thanks for noticing the issue.

What exactly is the problem? If the dataset has 1000 cells and update_cells removes 500 cells, doesn't batch_indices have dimension 500?
Can you maybe add some code to reproduce the problem? 

Thank you very much!

**Comment by adamgayoso** [comment] 2020-03-11 05:26
@ANazaret I think the issue is that if say cell type X is only among the 500 cells you removed then it doesn't update - same goes for labels. So the labels still map to cell types for which one was completeley removed.

**Comment by ANazaret** [comment] 2020-03-11 05:53
I see for labels and cell types. 
I think n_batches and batch_indices shouldn’t be changed (there are used as indexes in models). 
However, labels and cell types can be modified (with an info log because in scanvi the label id is also important ). 

Using `remap_cell_types` should work just fine.

**Comment by ANazaret** [comment] 2020-03-11 06:02
The function to call is
https://github.com/YosefLab/scVI/blob/3e8b1094c701d95d51dc4784839c062e98117701/scvi/dataset/dataset.py#L1240

Calling it without [“labels”] will remap all categorical attributes, which might be desirable?

By the way, I think we could make the log message clearer by giving the value of N https://github.com/YosefLab/scVI/blob/3e8b1094c701d95d51dc4784839c062e98117701/scvi/dataset/dataset.py#L650

**Comment by adamgayoso** [comment] 2020-06-27 18:34
Closing this as with the dataset refactor this function will no longer exist.

**Closed by adamgayoso** 2020-06-27 18:34 UTC
